name: salao_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  sqflite: ^2.2.8+4          # banco SQLite local
  path_provider: ^2.0.15     # para encontrar diretórios no dispositivo
  crypto: ^3.0.2             # para hash da senha
  path: ^1.8.3               # para manipulação de caminhos
  sqflite_common_ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg.jpg
    - assets/bg2.png
    - assets/elias.jpg
    - assets/bruna.jpg
    - assets/circular1.png
    - assets/bg3.png
    - assets/elias_logo1.png
    - assets/bg4.jpeg
    - assets/elias.png
    - assets/bruna.png